### ISSUE TITLE
Having a few issues running the project

### ISSUE THREAD

**Issue by Sterling-Malory-Archer** [michaelhaessig/ARFoundation-Image-On-Plane#1]
Hi Michael,

I came across your project as I wanted to make a similar one, however, when I tried to install your project I am getting a few errors, is it possible to update this project to 2019.3 and using AR Foundation 2.1.4?

**Comment by michaelhaessig** [comment]
Hi Strahinja, 

i guess it should be possible, however i am very much occupied with other projects at the moment i do not have the time to update this project.

If you manage to make it work with the newer versions a pull request is of course welcome :)

Best regards 
Michael

**Comment by kingbaggot** [comment]
Hi - thanks for the project - it builds fine on 2018.3 with the same set of ArFoundation/ArKit/ArCore - although the image seems to float around from the vertical plane it is attached to - Video of it here

https://drive.google.com/file/d/1eMlv1He0bWFYdvOvH_irkMEGVI8tvt-7/view?usp=sharing

I'm on a google pixel 2. Any idea what might be causing this ? 

** EDIT ** - I didn't see that I had to tap to "lock" it in position ! - all fine now. thanks :)

**Comment by michaelhaessig** [comment]
Thanks for the update, i'm closing the issue.
